config/routes.rb
Rails.application.routes.draw do
  root 'index#home'

  get 'about'=> 'index#about'

  get 'projects'=> 'index#projects'

  get 'education'=> 'index#education'

  get 'tapetrack'=> 'index#tapetrack'

  get 'cardfeed'=> 'index#cardfeed'

  get 'ihg'=> 'index#ihg'

  get 'moxie'=> 'index#moxie'

  get 'contact'=> 'index#contact'

  resources :homes

end

app/models/home.rb
class Home < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/index_controller.rb
class IndexController < ApplicationController
  def home
  end

  def about
  end

  def projects
  end

  def education
  end

  def tapetrack
  end

  def cardfeed
  end

  def ihg
  end

  def moxie
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/index_helper.rb
module IndexHelper
end

app/views/index/_uxdesign.html.erb
<div class="row">

<div class="col-md-4 padding">
    <h4>IHG Adventure App Design</h4>
    <%=link_to image_tag('ihgphone2.png'), ihg_path, target: '_blank'%>
    <p class="portdescription">A feature designed to implement into the current IHG rewards app and take advantage of location-based social media.</p>
</div>

<div class="col-md-4 padding">
  <h4>Cardfeed Mobile App Design</h4>
  <%=link_to image_tag('feedsmall.png'), cardfeed_path, target: '_blank'%>
  <p class="portdescription">A mobile application providing quick content curation and filter options with simple swipe interactions</p>
</div>

<div class="col-md-4 padding">
  <h4 class="margin-bottom">Moxie Virtual Reality Experience</h4>
  <%=link_to image_tag('oculusphoneview1.png'), moxie_path, target: '_blank'%>
  <p class="portdescription margin-top">Design for a retail experience within virtual reality.</p>
</div>

</div>

app/views/index/_webdev.html.erb
<div class="row">
  <div class="col-md-4 padding">
    <h4>Tapetrack Web App</h4>
     <%=link_to image_tag('tapetracksnap2.png'), tapetrack_path, target: '_blank'%>
     <p class="portdescription">A web application I built with Ruby on Rails, where users can build mix tapes and share them with friends.</p>
  </div>
</div>

app/views/index/about.html.erb
<div id= "hero">
	<%=image_tag("experience.png")%>
</div>
<div class="bottom_panel">

	<div class="row padding">
		<div class="col-md-4">

			<%=image_tag("florida.png")%>
			<p class="textcenter padding">Born in South Florida where I was spoiled with sunshine and salt water throughout my childhood, I've always enjoyed anything and everything that gets me outside. During that time, I had a habit of finding little projects for myself and family furniture that needed my artistic touch (others disagreed). I like to think that was the creative side deciding to take over.</p>
		</div>
		<div class="col-md-4">
			<%=image_tag("alabama.png")%>
			<p class="textcenter padding">My four years of college were spent at Auburn University. Vastly different and much smaller than my hometown, Auburn still managed to provide perspective and experiences I could've never expected. It was my junior year when I was introduced to HTML, and it was the first time work felt like fun.</p>
		</div>
		<div class="col-md-4">
			<%=image_tag("georgia.png")%>
			<p class="textcenter padding">I made the move to Atlanta upon receiving an internship at a hospitality PR agency and then a healthcare agency. At some point, I realized I wanted to be on the other side of the table. Days were spent learning about revolutionary ideas people were bringing to life, and I was eager to join the side of creation. Remembering how much I enjoyed coding and design, I began to explore my options and couldn't be happier with my decision.</p>
		</div>
	</div>
</div>

app/views/index/cardfeed.html.erb
    <div class="project_panel">
      <div class="row">
        <div class="col-md-6">
          <%=image_tag("cardfeed3.png")%></br>
          <a href="https://youtu.be/veYyOSpkfJg" target="_blank"<button class="btn btn-cf">Prototype Demo</button></a>
          <a href="http://fthdln.axshare.com/#p=home" target="_blank"<button class="btn btn-cf">Axure Prototype</button></a></br>
          <p class="padding">An independent project, CardFeed began as an idea designed and tailored to a single classmate's interests and needs. After an initial interview, the idea took shape as a news and content curator based on the user's interests. I later revisited the idea to expand user testing to others and elaborate on the first iteration. After four rounds of user testing and three primary iterations, CardFeed's final prototype features the ability to filter content by audio, text and video and move through the app with simple swipe motions.</p></br>


          <div class="row">
            <div class="col-md-6">
              <h3 class="cfblue">Product Goals</h3>
                <ul>
                  <li>Easily consume and share content.</li>
                  <li>Like or dislike content, tailoring future feed results.</li>
                  <li> Simple swipe motions allowing quick consumption, sharing and saving.</li>

            </div>
            <div class="col-md-6">
              <h3 class="cfblue">Design Tools</h3>
                <ul class="center">
                  <li>Sketch</li>
                  <li>Axure</li>
                </ul>
              </br>

            </div>
          </div>

        </div>
        <div class="col-md-6">
          <p></p>
          <%=image_tag("feed.png")%>
        </div>
      </div></br>

      <h3 class="cfblue">Process</h3></br>

      <div class="row padding">
        <div class="col-md-4">
          <%=image_tag("interview.png")%>
          <h4 class=>User Interview</h4>
          <p>The initial user interview pinpointed areas the user felt he could be served more efficiently. Together we decided a path for my design to pursue.</p>
        </div>
        <div class="col-md-4">
          <%=image_tag("sketching.png")%>
          <h4>Sketch</h4>
          <p>After sketching out simple designs to demonstrate functionality, I met with the user to get feedback and then implemented suggestions to create the first prototype. </p>
        </div>
        <div class="col-md-4">
          <%=image_tag("usertests.png")%>
          <h4>Prototyping + User Testing</h4>
          <p>Using the first prototype, I expanded user testing by sketching out additional ideas and observing user preference and interaction behavior. I repeated this step after the next three iterations to reach the final prototype.</p>
        </div>
      </div></br>


      <div class="row">
        <h3 class="cfblue">User Flow</h3>
        <div class="col-md-6">
          <%=image_tag('cfuserflow.png')%>
        </div>
        <div class="col-md-6">
          </br></br></br>
          <%=image_tag('ken.jpg')%>
        </div>
      </div>
    </div>

app/views/index/contact.html.erb
<h1>Index#contact</h1>
<p>Find me in app/views/index/contact.html.erb</p>

app/views/index/education.html.erb
<div id= "hero">
  <%=image_tag("education2.png")%>
</div>

<div class="bottom_panel">
	<div class= "row padding">
		<div class= "col-md-6">
			<%= image_tag('GA.png')%>
		</div>
		<div class= "col-md-6">

			<p class="education">I received formal UX design training while enrolled in General Assembly's 10 week UXDI Immersion program. With over 400 hours of class time, this course covered multiple areas of UX design including user testing, prototyping, information architecture, user flows, and site mapping. We also covered visual design basics including typography and color.</br>
			Axure, Sketch and Invision are just a few of the Software used in the completion of five projects.</p>
		</div>
	</div>
	<div class="row padding">
		<div class="col-md-6">
			<%=image_tag("TTS.png")%>
		</div>
		<div class="col-md-6">
			<p class="education2">In the summer of 2015, I enrolled in Tech Talent South's Web Development Immersion program. The structure of this program was very conducive to learning, with each day spent building a different project together. Before diving into Ruby on Rails, we covered HTML and CSS. We then built multiple web applications with Ruby on Rails, at times in teams to for experience with Github collaboration. A demo of my final, individual project for this course can be seen <a href="https://youtu.be/Q4B4C-4tkYo">here</a>.</p>
		</div>
	</div></br>
</div>

app/views/index/home.html.erb
<div>
	<div id="hero">
		<div class="row padding-top">
			<div class="col-md-4 padding-top">
				<div class="uxdev">UX</div>
          <p class="padding center p2">I love making people happy. When I first learned about UX, I realized it was a way to combine that with my desire to build things. The combination of creation, tech and people UX brings makes it, in my opinion, forever relevant and satisfying.</p>
          <a href="projects" target="_blank"><button class="btn btn-primary">View More</button></a>
			</div>

			<div class="col-md-4">
				<%=image_tag("headshot2.png")%>
				<center><div class="resume-button">
					<a href="https://drive.google.com/file/d/0B-TZYLQGy9cBU2owRTJkMFJya0U/view?usp=sharing" target="_blank"><button class="btn btn-primary">Resume</button></a>
				</div></center></br>
			</div>

			<div class="col-md-4 padding-top">
				<div class="uxdev">Web Dev</div>
				<p class="padding center p2">Learning both design and development was important to me. Other than selfish reasons (I love both), I wanted to bridge the gap between two important parts of a process to deliver quality, meaningful products.</p>
        <a href="projects" target="_blank"><button class="btn btn-primary">View More</button></a>
			</div>

		</div>

	</div>

<div class="bottom_panel">

	<div>
		<p class="padding center">*This website was built with Ruby on Rails and a little help from Bootstrap and Heroku.</p>
	</div>
</div>




</div>

app/views/index/ihg.html.erb
    <div class="project_panel">
      <div class="row">
        <div class="col-md-6">
          <p></p>
          <%=image_tag("IHG.png")%></br></br>
              <a href="http://ay87fx.axshare.com" target="_blank"<button class="btn btn-ihg">Axure Prototype</button></a>
              <a href="https://youtu.be/B6dHaPrZiyw" target="_blank"<button class="btn btn-ihg">Demo</button></a>
              <a href="https://drive.google.com/file/d/0B-TZYLQGy9cBMVpKMFlETzQ2TG8/view?usp=sharing" target="_blank"<button class="btn btn-ihg">Presentation</button></a>

          <p class="padding">This was a group project, myself and two classmates, in which we were assigned IHG Rewards. Given a prompt with general guidelines of what the hypothetical client desired, our team used a mixture of online survey, user testing, and our own research to achieve the final prototype.</p>


          <div class="row">
            <div class="col-md-6">
              <h3 class="ihgorange">Feature Goals</h3>
                <ul>
                  <li>Create a feature that takes advantage of location-based social media.</li>
                  <li>Increase awareness of IHG brand and rewards program.</li>
                </ul>
            </div>
            <div class="col-md-6">
              <h3 class="ihgorange">My Role</h3>
              <p class="center">For this project I wanted to focus on specific parts of the UX process that I felt needed practice. For that reason, I took the lead on surveying and user testing. During our in-person user testing, I walked the users through the app and practiced asking open questions to get valuable, usable feedback.</p>
              </br>

            </div>
          </div>

        </div>
        <div class="col-md-6">
          <p></p>
          <%=image_tag("ihgphone.png")%>
        </div>
      </div></br>

      <h3 class="ihgorange">Process</h3></br>

      <div class="row padding">
        <div class="col-md-12">
          <%=image_tag("survey.png")%>
          <h4>Initial Survey</h4>
          <p class="center padding">We began with an initial online survey using Qualtrics to help point us in the right direction. </br>We wanted the big questions answered:</br>
            Did people view rewards activity on a web app or mobile app? </br>
            What rewards programs were preferred?</br>
            If someone did use a rewards program, what would make it better, and if not, why?</br>
          </p>

        </div>
      </div></br>

      <div class="row">
        <div class="col-md-12">
          <%=image_tag("sketching.png")%>
          <h4>Feature Sketching</h4>
          <p class="center padding">Using our initial feedback, we headed to the whiteboard. Together, we each sketched out our vision and feature ideas and decided on key implementations. We pulled ideas from each other and eventually decided to send out a second survey to let users choose. In addition, we decided our design would be implemented into IHG's current rewards mobile app, since the survey revealed it as a prominent tool for users.</p>
          <%=image_tag("IHGsketches.png")%>
        </div>
      </div></br>

      <div class="row">
        <div class="col-md-12">
          <%=image_tag("survey.png")%>
          <h4> Second Survey</h4>
          <p class="center padding"> Our second survey helped reveal the most important features users wanted in a rewards app. It also pinpointed users' main issue with current rewards programs and how social media could be implemented.</p>
          <%=image_tag("IHGfeatures.png")%>
        </div>
      </div></br>

      <div class="row">
        <div class="col-md-12">
          <%=image_tag("usertests.png")%>
          <h4>Prototyping + User Testing</h4>
          <p class="center padding"> In the end, our prototype had four major iterations, each implementing user feedback. Our user testing ranged from other students to customers in the Ponce City Market food hall and employees at the Carter Center. With each round of feedback, we took what was consistent and applicable and worked on the next iteration.</p>
          <%=image_tag("IHGusertest.png")%></br>
          <%=image_tag("IHGiterations.png")%>
        </div>
      </div></br>

      <h3 class="ihgorange">Final Prototype</h3>
      <a href="https://youtu.be/B6dHaPrZiyw" target="_blank"<button class="btn btn-ihg">Demo</button></a>
      <p class="center padding"> Our final prototype centered on the idea that IHG rewards customers could perform easy, enjoyable tasks such as dining at a restaurant and sharing a picture on social media to earn small rewards and add to their overall point count. We believe IHG Adventure solves the users' main complaint which was that they could not travel enough to actually earn the current reward offerings. This made the program itself feel unreachable. Our features keep the customer interacting and engaged with the brand throughout their trip and reward them for things they most likely already do.</p>
      <p class="center padding"> For additional deliverables, please see our presentation slides
      <a href="https://drive.google.com/file/d/0B-TZYLQGy9cBMVpKMFlETzQ2TG8/view?usp=sharing" target="_blank"<button class="btn btn-ihg">Presentation</button></a>
      </p>
    </div>

app/views/index/moxie.html.erb
    <div class="project_panel">
      <%=image_tag('kenprototype.jpg')%>

      <div class="row row-mox">
        <div class="col-md-4">
          <h3 class="moxieorange">Challenge</h3>
          <p>Rethink the retail experience and create a new one compatible with all currently available VR headsets and the devices they support</p>
        </div>
        <div class="col-md-4 home-column">
          <a href="https://drive.google.com/file/d/0B-TZYLQGy9cBYnhRNXFodnpnUGM/view?usp=sharing" target="_blank"<button class="btn btn-mox">Presentation</button></a>
          <a href="https://youtu.be/Go1FAxBo2So?t=17m21s" target="_blank"<button class="btn btn-mox">Prototype Video</button></a>
        </div>
        <div class="col-md-4">
          <h3 class="moxieorange">Goals</h3>
          <p>Create a virtual reality retail experience that is not limited by physical or online retail, promoting and selling a next generation smart phone.</p>
        </div>
      </div>


      <div>
        <%=image_tag('moxielogo2.png')%>

      </div>

      <%=image_tag('divider.png')%>

      <div>
        <h3 class="moxieorange">Virtual Reality Research</h3>
        <%=image_tag('vrresearch.png')%>
        <div class="row">
          <div class="col-md-6">
           <p class="row-mox">We worked with the Future Experiences team to research what is possible with current VR technology. This allowed us to imagine, explore, and design what is possible when applying VR to the experience of purchasing a smart phone.</p>
          </div>
          <div class="col-md-6">
            <p class="row-mox">We began by visiting Moxie's future experience lab to try VR technology out for ourselves. We came away noting the natural tendency to use swipe motions and the frustration of being in virtual reality without being able to see or use your own hands.</p>
          </div>
        </div>
      </div>

      <%=image_tag('divider.png')%>

      <div>
      <h3 class="moxieorange">Sketches + Ideation</h3>
      <%=image_tag('vrsketches.png')%>
      <p class="row-mox">Just a few of my sketches from our week-long sketch and ideation sessions.</p>
        <div class="row">
          <div class="col-md-6">
            <p class="row-mox">With a challenge as vague as designing an experience with few boundaries and the instruction to let our imaginations run wild, it was important to spend plenty of time together and individually sketching as many ideas as possible to be sure we were taking advantage of the technology.</p>
          </div>
          <div class="col-md-6">
           <p class="row-mox"> What was unique about this project was the absolute necessity to give ourselves boundaries and guidelines in order to accomplish our goal within the three-week timeline. It could have been easy to drift and lose focus with the few boundaries we were given by the client, but our ability to work together to create a project plan and move through tasks helped us stay on track and ultimately surprise our client.</p>
         </div>
        </div>
      </div>

      <%=image_tag('divider.png')%>

      <div>
        <h3 class="moxieorange">Prototyping</h3>
        <div class="row">
          <div class="col-md-4">
            <p class="row-mox">Solving the challenge of creating a virtual reality prototype was our first major hurdle.</p>
          </div>
          <div class="col-md-4">
            <p class="row-mox">We reached out to VR companies and teams for advice on how to rapid prototype for VR, and were unable to find a solution that didn't involve coding in Unity and spending at least a few weeks actually building a product.<p>
          </div>
          <div class="col-md-4">
            <p class="row-mox">Our team saw this as an opportunity to get our craft helmets on and implement some efficiency into the VR design process.</p>
          </div>
        </div>

        <%=image_tag('vrpaperprototype.png')%>
        <%=image_tag('bodystorming.gif')%>
        <div class="row">
          <div class="col-md-6">
            <p class="row-mox">Instead of weeks, we spent one day sketching on giant sheets of paper and tables. Each of our VR scenes were drawn across four sheets of paper and attached to upright tables.</p>
          </div>
          <div class="col-md-6">
            <p class="row-mox">During user testing, the user was presented each scene by flipping it over the table to land infront of them. As they made decisions and we noted their behavior with the options presented to them, we were able to iterate with simple, quick sketches and reordering scenes.</p>
          </div>
        </div>

      </div>

      <%=image_tag('divider.png')%></br>


      <div>
        <p class="row-mox">To view the full digital prototype filmed during out presentation to Moxie, please click <a href="https://youtu.be/Go1FAxBo2So?t=17m21s" target="_blank"<button class="btn btn-mox">Prototype Video</button></a></p>
      </div></br>
    </div>

app/views/index/projects.html.erb
<div id= "hero">
  <%= image_tag('projects31.png')%></br>
  <p id="ux" class="l-inline-block projectfilter clickable">UX</p>
  <p id="webdev" class="l-inline-block projectfilter clickable">Web Dev</p>
  <p id="all" class="l-inline-block projectfilter textdecoration clickable">All</p>
  <p class="clickimagetext">Click project images for more info</p>
</div>

<div id="uxtwo" class="bottom_panel">
  <%= link_to render(:partial => 'uxdesign')%>
</div>

<div id="webdevtwo" class="bottom_panel">
  <%= link_to render(:partial => 'webdev')%>
</div>

app/views/index/tapetrack.html.erb
<div class="project_panel">
  <div class="row tapetrack">
    <div class="col-md-6">
      <%=image_tag("tapetracksnap2.png")%>
      <p class="padding">My first web application, Tapetrack was inspired by an idea I held on to for a while and finally built the skills to create. The idea is an application allowing users to create mixtapes for others in the digital space and elicit as many 90's flashbacks as possible. I plan to keep playing with and adding to this project for fun and to continue building my skills. </p></br>
    </div>
    <div class="col-md-6">
      <p class="padding"><%= image_tag("tools.png")%>
                    Ruby on Rails,
                    Bootstrap
      </p>
      <p><a href="https://youtu.be/Q4B4C-4tkYo" target="_blank"><button class="btn btn-tt">App Demo</button></a></p>
      </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Portfolio</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
  <%= favicon_link_tag 'favicon.png' %>
</head>
<body>
		<center>
  		<div class="top">
  			<div class="row bar">
  				<div class="col-md-4">
  					<%= button_to "Projects", projects_path, :class=> "navbutton", :method => :get%>
  				</div>
  				<div class="col-md-4">
  					<%= button_to "Education", education_path, :class=> "navbutton", :method => :get%>
  				</div>
  				<div class="col-md-4">
  					<%= button_to "About", about_path, :class=> "navbutton", :method => :get%>
  				</div>
        </div>
        <!-- <div class="pull-right">
          <a href="mailto:stephjanecz@gmail.com" target="_blank"><%=image_tag('mail.png')%></a>
          <a href="https://www.linkedin.com/in/stephanieczajkowski" target="_blank"><%=image_tag('linkedin.png')%></a>
          <a href="http://uxnfrecks.tumblr.com/" target="_blank"><%=image_tag('tumblr.png')%></a>
          <a href="https://github.com/stephjane" target="_blank"><%=image_tag('github.png')%></a>
        </div> -->
  		</div>
      <a href="/"><p id="name" class="margin-0 uppercase">stephanie czajkowski</p></a>
		</center>




		<center>
			<div class="container">
			<%= yield %>
			</div>
		</center>

</body>

</html>